### PR TITLE
[WIP] Ignore forwards

### PR DESCRIPTION
**Pull request by Lonami**
It's annoying.

### CODE REVIEW

**Comment by Lonami** [comment]
You probably don't want those `print`'s flooding `stdout`.

**Comment by Lonami** [comment]
Aw, GitHub doesn't mark this as a draft. Anyway after further discussion, forwards should **not** be ignored in private.

**Comment by Sharparam** [comment]
To make a PR draft you have to select that option when making the PR with the dropdown next to the "create" button.

**Comment by Lonami** [comment]
The problem is "**when** making the PR"

**Comment by Lonami** [comment]
Closing because #13 will break this.

**Pull request closed without merging**
