### PR TITLE
Clean up a little

### PR DESCRIPTION
**Pull request by 9ary**
- Removed unused `json` import
- Use `defaultdict` as intended, and replace the manually maintained FIFO `list` with a `deque`
- Clean up duplicate code

### CODE REVIEW

**Review by Lonami — APPROVED** [review]

**Comment by 9ary** [comment]
If you're running this on Python 3.5, I'd also suggest switching to f-strings over `.format()` since it's faster.

**Comment by Lonami** [comment]
You mean Python 3.6?

**Comment by 9ary** [comment]
Yeah you're right, my bad.

**Comment by vijfhoek** [comment]
thank

**Pull request merged**
